apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    #ports accessible inside the cluster
    port: 8080
    #ports to forward to inside the pod
    targetPort: 80
    #ports accessible outside cluster
    nodePort: 32767
  type: LoadBalancer